version: '3'
services:
  db:
    image: mysql:latest
    container_name: laravel
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
    volumes:
      - db_data:/var/lib/mysql
volumes:
    db_data:
